baseURL = "https://matejsmycka.github.io/web/"
languageCode = "en-us"
title = "Matej Smycka"
themesDir = "./"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = ""
    url = "/"
    weight = 1

[[menu.main]]
    name = "Home"
    url = "/contents/"
    weight = 2

[params]
  google_analytics_id="G-54DDM7XNG7"
  homepage_button_link = '/web/contents/'
  homepage_button_text = 'Continue'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  # homepage_image = '/images/'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.logo]
      # mobile = "/images/logo.svg"
      # standard  = "/images/logo.svg"
